//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokedexAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pokemon
    {
        

        public int pokeid { get; set; }
        public string name { get; set; }
        public byte[] sprite { get; set; }
        public int id { get; set; }
    }
   public class PokemonList
    {
        public PokemonList()
        {
            PokemonsLists=new List<Pokemon>();
        }
        public List<Pokemon> PokemonsLists { set; get; }
    }

    
}
