//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokedexAPI
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Pokemon
    {
        public int PokemonId { get; set; }
        [JsonProperty(PropertyName = "name")]
        public string PokemonName { get; set; }
        public byte[] Sprite { get; set; }
        [JsonProperty(PropertyName = "id")]
        public Nullable<int> Id { get; set; }
    }
}
